#!/usr/bin/env bash
set -ex

readonly BUILDROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

brew update
brew unlink pkg-config
brew install asciidoc gengetopt hidapi libu2f-host libu2f-server pkg-config check

pushd "$BUILDROOT" &>/dev/null
  ./autogen.sh && ./configure --disable-silent-rules --disable-man && make
popd &>/dev/null
