#!/usr/bin/env bash
set -ex

readonly BUILDROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."

sudo apt-get update -qq && sudo apt-get install -qq -y --no-install-recommends  \
  libpam-dev asciidoc gengetopt docbook-xsl xsltproc libxml2-utils              \
  libjson0-dev check help2man libudev-dev libusb-1.0-0-dev


pushd "/tmp" &>/dev/null
  export PKG_CONFIG_PATH=/tmp/hidapi/pc:$PKG_CONFIG_PATH
  git clone git://github.com/signal11/hidapi.git
  pushd "/tmp/hidapi" &>/dev/null
    ./bootstrap && ./configure && make && sudo make install
    sudo ldconfig
  popd &>/dev/null

  export PKG_CONFIG_PATH=/tmp/libu2f-server/u2f-server:$PKG_CONFIG_PATH
  git clone https://github.com/yubico/libu2f-server.git
  pushd "/tmp/libu2f-server" &>/dev/null
    ./autogen.sh && ./configure --disable-h2a && make && sudo make install
    sudo ldconfig
  popd &>/dev/null

  export PKG_CONFIG_PATH=/tmp/libu2f-host/u2f-host:$PKG_CONFIG_PATH
  git clone https://github.com/yubico/libu2f-host.git
  pushd "/tmp/libu2f-host" &>/dev/null
    ./autogen.sh && ./configure && make && sudo make install
    sudo ldconfig
  popd &>/dev/null
popd &>/dev/null

pushd "$BUILDROOT" &>/dev/null
  ./autogen.sh && ./configure --disable-silent-rules && make check
popd &>/dev/null
