#!/usr/bin/env bash
set -evx
env | sort

if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  ./build-aux/travis-build-osx
elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  ./build-aux/travis-build-linux
else
  >&2 echo "Unknown OS: $TRAVIS_OS_NAME"
  exit 1
fi
