#!/bin/sh
set -e
set -x

HERE=$PWD
cd /tmp

export PKG_CONFIG_PATH=/tmp/hidapi/pc:$PKG_CONFIG_PATH
git clone git://github.com/signal11/hidapi.git
cd hidapi
./bootstrap && ./configure && make && sudo make install

cd ..

export PKG_CONFIG_PATH=/tmp/libu2f-server/u2f-server:$PKG_CONFIG_PATH
git clone https://github.com/yubico/libu2f-server.git
cd libu2f-server
autoreconf -i
./configure && make && sudo make install

cd ..

export PKG_CONFIG_PATH=/tmp/libu2f-host/u2f-host:$PKG_CONFIG_PATH
git clone https://github.com/yubico/libu2f-host.git
cd libu2f-host
autoreconf -i
./configure && make && sudo make install

sudo ldconfig

cd $HERE

autoreconf -i && ./configure && make check
